title: Ashutosh Kumar
description: Personal website of Ashutosh Kumar

theme: just-the-docs

url: https://ashu1069.github.io
baseurl: ""

# nav_external_links:
#   - title: Research
#     url: /docs/research
#   - title: Blog
#     url: /docs/blog
#   - title: Resume
#     url: /docs/resume

aux_links:
  '<i class="fab fa-github"></i> GitHub': https://github.com/ashu1069

aux_links_new_tab: true

# Optional: Add these if you want to customize your site further
# color_scheme: dark
# logo: "/assets/images/logo.png"
# favicon_ico: "/assets/images/favicon.ico"